import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  serviceOne,
  serviceTwo,
  serviceThree,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  user1,
  user2,
  user3,
  user4,
  user5,
  user6,
  user7,
  user8,
  user9,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1002,
    title: "Services",
    link: "/services",
  },
  {
    _id: 1002,
    title: "Accomodation",
    link: "/accomodation",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  // {
  //   _id: 1005,
  //   title: "Journal",
  //   link: "/journal",
  // },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1005,
    img: serviceOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1006,
    img: serviceTwo,
    productName: "New Backpack",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1007,
    img: serviceThree,
    productName: "Household materials",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1013,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },

  {
    _id: 1014,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1015,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1016,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1018,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1019,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1020,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1021,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1022,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1023,
    img: serviceOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1024,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1025,
    img: spfTwo,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1027,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1028,
    img: serviceOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1029,
    img: serviceTwo,
    productName: "New Backpack",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1030,
    img: serviceThree,
    productName: "Household materials",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1033,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1036,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1037,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  // {
  //   _id: 1039,
  //   img: bestSellerFour,
  //   productName: "Travel Bag",
  //   price: "220.00",
  //   color: "Black",
  //   badge: false,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1041,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1045,
    img: serviceOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1046,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== PaginationItems End here =================

// =================== Shop Items Start here ===============

export const shopItems = [
  {
    _id: 1101,
    userImg: user1 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 11,
    img: newArrOne ,
    productName: "Nike Airforce",
    price: 350,
    condition: "New",
    des: "Original Size 8.",
    badge: true,
    category: ["clothing", "popular"],
  },
  {
    _id: 1102,
    userImg: user2 ,
    userName: "Themba Ndlovu ",
    userRating: 3,
    userSales: 11,
    img: newArrTwo ,
    productName: "Couch",
    price: 650,
    condition: "Used",
    des: "4 seater couch still in usable condition.",
    badge: true,
    category: ["furniture", "House Items"],
  },
  {
    _id: 1103,
    userImg:  user3 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 8,
    img:  newArrThree ,
    productName: "Used bicycle.",
    price: 2500,
    condition: "Used",
    des: "Used bicycle. As good as new.",
    badge: true,
    category: ["machanic"],
  },
  {
    _id: 1102,
    userImg: user2 ,
    userName: "Themba Ndlovu ",
    userRating: 3,
    userSales: 11,
    img: newArrTwo ,
    productName: "Couch",
    price: 650,
    condition: "Used",
    des: "4 seater couch still in usable condition.",
    badge: true,
    category: ["furniture"],
  },
    {
    _id: 1103,
    userImg:  user3 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 8,
    img:  newArrThree ,
    productName: "Used bicycle.",
    price: 2500,
    condition: "Used",
    des: "Used bicycle. As good as new.",
    badge: true,
    category: ["bike"],
  },
  {
    _id: 1101,
    userImg:  user1 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 11,
    img: newArrOne ,
    productName: "Nike Airforce",
    price: 350,
    condition: "New",
    des: "Original Size 8.",
    badge: true,
    category: ["clothing"],
  },
      {
    _id: 1103,
    userImg:  user3 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 8,
    img:  newArrThree ,
    productName: "Used bicycle.",
    price: 2500,
    condition: "Used",
    des: "Used bicycle. As good as new.",
    badge: true,
    category: ["bike"],
  },
    {
    _id: 1102,
    userImg: user2 ,
    userName: "Themba Ndlovu ",
    userRating: 3,
    userSales: 11,
    img: newArrTwo ,
    productName: "Couch",
    price: 650,
    condition: "Used",
    des: "4 seater couch still in usable condition.",
    badge: true,
    category: ["furniture"],
  },
   {
    _id: 1101,
    userImg:  user1 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 11,
    img:  newArrOne ,
    productName: "Nike Airforce",
    price: 350,
    condition: "New",
    des: "Original Size 8.",
    badge: true,
    category: ["clothing"],
  },
   {
    _id: 1101,
    userImg:  user1 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 11,
    img:  newArrOne ,
    productName: "Nike Airforce",
    price: 350,
    condition: "New",
    des: "Original Size 8.",
    badge: true,
    category: ["clothing"],
  },
  {
    _id: 1102,
    userImg: user2 ,
    userName: "Themba Ndlovu ",
    userRating: 3,
    userSales: 11,
    img: newArrTwo ,
    productName: "Couch",
    price: 650,
    condition: "Used",
    des: "4 seater couch still in usable condition.",
    badge: true,
    category: ["furniture"],
  },
  {
    _id: 1103,
    userImg:  user3 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 8,
    img:  newArrThree ,
    productName: "Used bicycle.",
    price: 2500,
    condition: "Used",
    des: "Used bicycle. As good as new.",
    badge: true,
    category: ["bike"],
  },
  {
    _id: 1102,
    userImg: user2 ,
    userName: "Themba Ndlovu ",
    userRating: 3,
    userSales: 11,
    img: newArrTwo ,
    productName: "Couch",
    price: 650,
    condition: "Used",
    des: "4 seater couch still in usable condition.",
    badge: true,
    category: ["furniture"],
  },
    {
    _id: 1103,
    userImg:  user3 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 8,
    img:  newArrThree ,
    productName: "Used bicycle.",
    price: 2500,
    condition: "Used",
    des: "Used bicycle. As good as new.",
    badge: true,
    category: ["bike"],
  },
  {
    _id: 1101,
    userImg:  user1 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 11,
    img:  newArrOne ,
    productName: "Nike Airforce",
    price: 350,
    condition: "New",
    des: "Original Size 8.",
    badge: true,
    category: ["clothing"],
  },
      {
    _id: 1103,
    userImg:  user3 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 8,
    img:  newArrThree ,
    productName: "Used bicycle.",
    price: 2500,
    condition: "Used",
    des: "Used bicycle. As good as new.",
    badge: true,
    category: ["bike"],
  },
    {
    _id: 1102,
    userImg: user2 ,
    userName: "Themba Ndlovu ",
    userRating: 3,
    userSales: 11,
    img: newArrTwo ,
    productName: "Couch",
    price: 650,
    condition: "Used",
    des: "4 seater couch still in usable condition.",
    badge: true,
    category: ["furniture"],
  },
   {
    _id: 1101,
    userImg:  user1 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 11,
    img:  newArrOne ,
    productName: "Nike Airforce",
    price: 350,
    condition: "New",
    des: "Original Size 8.",
    badge: true,
    category: ["clothing"],
  },
   {
    _id: 1101,
    userImg:  user1 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 11,
    img:  newArrOne ,
    productName: "Nike Airforce",
    price: 350,
    condition: "New",
    des: "Original Size 8.",
    badge: true,
    category: ["clothing"],
  },
  {
    _id: 1102,
    userImg: user2 ,
    userName: "Themba Ndlovu ",
    userRating: 3,
    userSales: 11,
    img: newArrTwo ,
    productName: "Couch",
    price: 650,
    condition: "Used",
    des: "4 seater couch still in usable condition.",
    badge: true,
    category: ["furniture"],
  },
  {
    _id: 1103,
    userImg:  user3 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 8,
    img:  newArrThree ,
    productName: "Used bicycle.",
    price: 2500,
    condition: "Used",
    des: "Used bicycle. As good as new.",
    badge: true,
    category: ["bike"],
  },
  {
    _id: 1102,
    userImg: user2 ,
    userName: "Themba Ndlovu ",
    userRating: 3,
    userSales: 11,
    img: newArrTwo ,
    productName: "Couch",
    price: 650,
    condition: "Used",
    des: "4 seater couch still in usable condition.",
    badge: true,
    category: ["furniture"],
  },
    {
    _id: 1103,
    userImg:  user3 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 8,
    img:  newArrThree ,
    productName: "Used bicycle.",
    price: 2500,
    condition: "Used",
    des: "Used bicycle. As good as new.",
    badge: true,
    category: ["bike"],
  },
  {
    _id: 1101,
    userImg:  user1 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 11,
    img:  newArrOne ,
    productName: "Nike Airforce",
    price: 350,
    condition: "New",
    des: "Original Size 8.",
    badge: true,
    category: ["clothing"],
  },
      {
    _id: 1103,
    userImg:  user3 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 8,
    img:  newArrThree ,
    productName: "Used bicycle.",
    price: 2500,
    condition: "Used",
    des: "Used bicycle. As good as new.",
    badge: true,
    category: ["bike"],
  },
    {
    _id: 1102,
    userImg: user2 ,
    userName: "Themba Ndlovu ",
    userRating: 3,
    userSales: 11,
    img: newArrTwo ,
    productName: "Couch",
    price: 650,
    condition: "Used",
    des: "4 seater couch still in usable condition.",
    badge: true,
    category: ["furniture"],
  },
   {
    _id: 1101,
    userImg:  user1 ,
    userName: "Sarah Brown ",
    userRating: 4,
    userSales: 11,
    img:  newArrOne ,
    productName: "Nike Airforce",
    price: 350,
    condition: "New",
    des: "Original Size 8.",
    badge: true,
    category: ["clothing"],
  },
   
];

// =================== Shop Items End here =================

// =================== Services Items Start here ===============

export const serviceItems = [
  {
    _id: 1111,
    userImg: user4 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 11,
    img: serviceOne ,
    serviceName: "Garden Services",
    price: 350,
    location: "Johannesburg North",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["garden"],
  },
  {
    _id: 1112,
    userImg: user5 ,
    userName: "Amanda Botha ",
    userRating: 3,
    userSales: 11,
    img: serviceTwo ,
    serviceName: "Solar System Installers",
    price: 650,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["solar"],
  },
  {
    _id: 1113,
    userImg:  user6 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 8,
    img:  serviceThree ,
    serviceName: "Machanic",
    price: 500,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["machanic"],
  },
  {
    _id: 1112,
    userImg: user5 ,
    userName: "Amanda Botha ",
    userRating: 3,
    userSales: 11,
    img: serviceTwo ,
    serviceName: "Solar System Installers",
    price: 650,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["solar"],
  },
    {
    _id: 1113,
    userImg:  user6 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 8,
    img:  serviceThree ,
    serviceName: "Machanic",
    price: 500,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["machanic"],
  },
  {
    _id: 1111,
    userImg:  user4 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 11,
    img: serviceOne ,
    serviceName: "Garden Services",
    price: 350,
    location: "Johannesburg North",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["garden"],
  },
      {
    _id: 1113,
    userImg:  user6 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 8,
    img:  serviceThree ,
    serviceName: "Machanic",
    price: 500,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["machanic"],
  },
    {
    _id: 1112,
    userImg: user5 ,
    userName: "Amanda Botha ",
    userRating: 3,
    userSales: 11,
    img: serviceTwo ,
    serviceName: "Solar System Installers",
    price: 650,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["solar"],
  },
   {
    _id: 1111,
    userImg:  user4 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 11,
    img:  serviceOne ,
    serviceName: "Garden Services",
    price: 350,
    location: "Johannesburg North",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["garden"],
  },
   {
    _id: 1111,
    userImg:  user4 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 11,
    img:  serviceOne ,
    serviceName: "Garden Services",
    price: 350,
    location: "Johannesburg North",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["garden"],
  },
  {
    _id: 1112,
    userImg: user5 ,
    userName: "Amanda Botha ",
    userRating: 3,
    userSales: 11,
    img: serviceTwo ,
    serviceName: "Solar System Installers",
    price: 650,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["solar"],
  },
  {
    _id: 1113,
    userImg:  user6 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 8,
    img:  serviceThree ,
    serviceName: "Machanic",
    price: 500,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["machanic"],
  },
  {
    _id: 1112,
    userImg: user5 ,
    userName: "Amanda Botha ",
    userRating: 3,
    userSales: 11,
    img: serviceTwo ,
    serviceName: "Solar System Installers",
    price: 650,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["solar"],
  },
    {
    _id: 1113,
    userImg:  user6 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 8,
    img:  serviceThree ,
    serviceName: "Machanic",
    price: 500,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["machanic"],
  },
  {
    _id: 1111,
    userImg:  user4 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 11,
    img:  serviceOne ,
    serviceName: "Garden Services",
    price: 350,
    location: "Johannesburg North",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["garden"],
  },
      {
    _id: 1113,
    userImg:  user6 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 8,
    img:  serviceThree ,
    serviceName: "Machanic",
    price: 500,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["machanic"],
  },
    {
    _id: 1112,
    userImg: user5 ,
    userName: "Amanda Botha ",
    userRating: 3,
    userSales: 11,
    img: serviceTwo ,
    serviceName: "Solar System Installers",
    price: 650,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["solar", "popular"],
  },
   {
    _id: 1111,
    userImg:  user4 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 11,
    img:  serviceOne ,
    serviceName: "Garden Services",
    price: 350,
    location: "Johannesburg North",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["garden"],
  },
   {
    _id: 1111,
    userImg:  user4 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 11,
    img:  serviceOne ,
    serviceName: "Garden Services",
    price: 350,
    location: "Johannesburg North",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["garden"],
  },
  {
    _id: 1112,
    userImg: user5 ,
    userName: "Amanda Botha ",
    userRating: 3,
    userSales: 11,
    img: serviceTwo ,
    serviceName: "Solar System Installers",
    price: 650,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["solar"],
  },
  {
    _id: 1113,
    userImg:  user6 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 8,
    img:  serviceThree ,
    serviceName: "Machanic",
    price: 500,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["machanic"],
  },
  {
    _id: 1112,
    userImg: user5 ,
    userName: "Amanda Botha ",
    userRating: 3,
    userSales: 11,
    img: serviceTwo ,
    serviceName: "Solar System Installers",
    price: 650,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["solar"],
  },
    {
    _id: 1113,
    userImg:  user6 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 8,
    img:  serviceThree ,
    serviceName: "Machanic",
    price: 500,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["machanic"],
  },
  {
    _id: 1111,
    userImg:  user4 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 11,
    img:  serviceOne ,
    serviceName: "Garden Services",
    price: 350,
    location: "Johannesburg North",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["garden"],
  },
      {
    _id: 1113,
    userImg:  user6 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 8,
    img:  serviceThree ,
    serviceName: "Machanic",
    price: 500,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["machanic"],
  },
    {
    _id: 1112,
    userImg: user5 ,
    userName: "Amanda Botha ",
    userRating: 3,
    userSales: 11,
    img: serviceTwo ,
    serviceName: "Solar System Installers",
    price: 650,
    location: "Gauteng",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["solar"],
  },
   {
    _id: 1111,
    userImg:  user4 ,
    userName: "Amy Jones ",
    userRating: 4,
    userSales: 11,
    img:  serviceOne ,
    serviceName: "Garden Services",
    price: 350,
    location: "Johannesburg North",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["garden"],
  },
   
];

// =================== Services Items End here =================

// =================== Accomodation Items Start here ===============

export const accomodationItems = [
  {
    _id: 1014,
    userImg: user7 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 11,
    img: spfOne ,
    accomodationTitle: "Garden Cottage",
    price: 2500,
    location: "Randburg",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["garden"],
  },
  {
    _id: 1015,
    userImg: user8 ,
    userName: "Mat Black ",
    userRating: 3,
    userSales: 11,
    img: spfTwo ,
    accomodationTitle: "Breakfast & Bed",
    price: 1250,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["shortStay"],
  },
  {
    _id: 1113,
    userImg:  user9 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 8,
    img:  spfThree ,
    accomodationTitle: "1 bed Flat",
    price: 5000,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["flat", "rentals"],
  },
  {
    _id: 1015,
    userImg: user8 ,
    userName: "Mat Black ",
    userRating: 3,
    userSales: 11,
    img: spfTwo ,
    accomodationTitle: "Breakfast & Bed",
    price: 1250,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["shortStay"],
  },
    {
    _id: 1113,
    userImg:  user9 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 8,
    img:  spfThree ,
    accomodationTitle: "1 bed Flat",
    price: 5000,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["flat", "rentals"],
  },
  {
    _id: 1014,
    userImg:  user7 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 11,
    img: spfOne ,
    accomodationTitle: "Garden Cottage",
    price: 2500,
    location: "Randburg",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["cottage"],
  },
      {
    _id: 1113,
    userImg:  user9 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 8,
    img:  spfThree ,
    accomodationTitle: "1 bed Flat",
    price: 5000,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["flat", "rentals"],
  },
    {
    _id: 1015,
    userImg: user8 ,
    userName: "Mat Black ",
    userRating: 3,
    userSales: 11,
    img: spfTwo ,
    accomodationTitle: "Breakfast & Bed",
    price: 1250,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["shortStay"],
  },
   {
    _id: 1014,
    userImg:  user7 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 11,
    img:  spfOne ,
    accomodationTitle: "Garden Cottage",
    price: 2500,
    location: "Randburg",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["cottage"],
  },
   {
    _id: 1014,
    userImg:  user7 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 11,
    img:  spfOne ,
    accomodationTitle: "Garden Cottage",
    price: 2500,
    location: "Randburg",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["cottage"],
  },
  {
    _id: 1015,
    userImg: user8 ,
    userName: "Mat Black ",
    userRating: 3,
    userSales: 11,
    img: spfTwo ,
    accomodationTitle: "Breakfast & Bed",
    price: 1250,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["shortStay"],
  },
  {
    _id: 1113,
    userImg:  user9 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 8,
    img:  spfThree ,
    accomodationTitle: "1 bed Flat",
    price: 5000,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["flat", "rentals"],
  },
  {
    _id: 1015,
    userImg: user8 ,
    userName: "Mat Black ",
    userRating: 3,
    userSales: 11,
    img: spfTwo ,
    accomodationTitle: "Breakfast & Bed",
    price: 1250,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["shortStay"],
  },
    {
    _id: 1113,
    userImg:  user9 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 8,
    img:  spfThree ,
    accomodationTitle: "1 bed Flat",
    price: 5000,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["flat", "rentals"],
  },
  {
    _id: 1014,
    userImg:  user7 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 11,
    img:  spfOne ,
    accomodationTitle: "Garden Cottage",
    price: 2500,
    location: "Randburg",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["cottage"],
  },
      {
    _id: 1113,
    userImg:  user9 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 8,
    img:  spfThree ,
    accomodationTitle: "1 bed Flat",
    price: 500,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["flat", "rentals"],
  },
    {
    _id: 1015,
    userImg: user8 ,
    userName: "Mat Black ",
    userRating: 3,
    userSales: 11,
    img: spfTwo ,
    accomodationTitle: "Breakfast & Bed",
    price: 1250,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["shortStay"],
  },
   {
    _id: 1014,
    userImg:  user7 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 11,
    img:  spfOne ,
    accomodationTitle: "Garden Cottage",
    price: 2500,
    location: "Randburg",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["cottage"],
  },
   {
    _id: 1014,
    userImg:  user7 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 11,
    img:  spfOne ,
    accomodationTitle: "Garden Cottage",
    price: 2500,
    location: "Randburg",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["cottage"],
  },
  {
    _id: 1015,
    userImg: user8 ,
    userName: "Mat Black ",
    userRating: 3,
    userSales: 11,
    img: spfTwo ,
    accomodationTitle: "Breakfast & Bed",
    price: 1250,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["shortStay"],
  },
  {
    _id: 1113,
    userImg:  user9 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 8,
    img:  spfThree ,
    accomodationTitle: "1 bed Flat",
    price: 5000,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["flat", "rentals"],
  },
  {
    _id: 1015,
    userImg: user8 ,
    userName: "Mat Black ",
    userRating: 3,
    userSales: 11,
    img: spfTwo ,
    accomodationTitle: "Breakfast & Bed",
    price: 1250,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["shortStay"],
  },
    {
    _id: 1113,
    userImg:  user9 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 8,
    img:  spfThree ,
    accomodationTitle: "1 bed Flat",
    price: 5000,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["flat", "rentals"],
  },
  {
    _id: 1014,
    userImg:  user7 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 11,
    img:  spfOne ,
    accomodationTitle: "Garden Cottage",
    price: 2500,
    location: "Randburg",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["cottage"],
  },
      {
    _id: 1113,
    userImg:  user9 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 8,
    img:  spfThree ,
    accomodationTitle: "1 bed Flat",
    price: 5000,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["flat", "rentals"],
  },
    {
    _id: 1015,
    userImg: user8 ,
    userName: "Mat Black ",
    userRating: 3,
    userSales: 11,
    img: spfTwo ,
    accomodationTitle: "Breakfast & Bed",
    price: 1250,
    location: "Sandton",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis..",
    badge: true,
    category: ["shortStay"],
  },
   {
    _id: 1014,
    userImg:  user7 ,
    userName: "Joe Wills ",
    userRating: 4,
    userSales: 11,
    img:  spfOne ,
    accomodationTitle: "Garden Cottage",
    price: 2500,
    location: "Randburg",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis...",
    badge: true,
    category: ["cottage"],
  },
   
];

